# Generated by Django 5.2.7 on 2025-11-01 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0004_animal_fecha_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionLeche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('litros', models.FloatField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='animales.animal')),
            ],
        ),
    ]
