# Generated by Django 5.2.7 on 2025-11-08 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0006_animal_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Gestación', 'En Gestación'), ('Vacía', 'Vacía')], max_length=20)),
                ('fecha_palpacion', models.DateField()),
                ('tiempo_gestacion', models.IntegerField(help_text='Días estimados de gestación')),
                ('proxima_palpacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestaciones', to='animales.animal')),
            ],
        ),
    ]
