# Generated by Django 5.2.7 on 2025-11-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestacion',
            name='tiempo_gestacion',
            field=models.IntegerField(blank=True, help_text='Días estimados de gestación', null=True),
        ),
    ]
