# Generated by Django 5.2.7 on 2025-10-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAnimal', models.CharField(max_length=10, unique=True)),
                ('chip', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo', models.CharField(choices=[('Bufalo', 'Búfalo'), ('Vacuno', 'Vacuno')], max_length=10)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('procedencia', models.CharField(max_length=100)),
                ('partos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('produccionLeche', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medicion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
