# Generated by Django 5.2.7 on 2025-10-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='medicion',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='partos',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='produccionLeche',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='updated_at',
        ),
    ]
