# Generated by Django 5.2.7 on 2025-10-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_remove_animal_created_at_remove_animal_medicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='codigo_madre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='codigo_padre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='embarazada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_palpacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_parto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='medicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='origen',
            field=models.CharField(choices=[('Nacimiento', 'Nacimiento'), ('Compra', 'Compra')], default='Nacimiento', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='partos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='produccionLeche',
            field=models.FloatField(default=0),
        ),
    ]
