# Generated by Django 5.2.7 on 2025-10-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_animal_codigo_madre_animal_codigo_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
