# Generated by Django 5.2.7 on 2025-11-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_animal_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='chip2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='chip3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
    ]
