# Generated by Django 5.2.7 on 2025-11-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0005_animal_chip2_animal_chip3_alter_animal_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
